// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "bdk-rn.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "BdkRnSpec.h"

@interface BdkRn : NSObject <NativeBdkRnSpec>
#else
#import <React/RCTBridgeModule.h>

@interface BdkRn : NSObject <RCTBridgeModule>
#endif

@end